### ISSUE TITLE
Theme not working on sprint 42

### ISSUE THREAD

**Issue by rpereira** [Brackets-Themes/EasyDark#3]
I've tested in more than one computer running the latest Brackets release and after selecting this theme nothing happens.

**Comment by MiguelCastillo** [comment]
@ruiafonsopereira Hi yeah I know... :/  Here is more information about it.  https://github.com/Brackets-Themes/EasyDark/issues/1

It will get fixed soon.  Thank you for testing it.

**Comment by MiguelCastillo** [comment]
@ruiafonsopereira I just uploaded a version that works in 42 release.  Thank you reporting this and let me know if you have any other issues.
